global:
  checkNewVersion: true
  sendAnonymousUsage: true

entryPoints:
  web:
    address: :80
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32"
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"

log:
  level: INFO
  filePath: /var/log/traefik.log

accessLog:
  filePath: /var/log/traefik-access.log

api:
  dashboard: true
  insecure: true

providers:
  swarm:
    network: traefiknet
    exposedByDefault: false

ping: {}

# Middleware tambahan untuk keamanan
http:
  middlewares:
    real-ip:
      headers:
        customRequestHeaders:
          X-Real-IP: "X-Real-IP"
          X-Forwarded-For: "X-Forwarded-For"
          X-Forwarded-Proto: "X-Forwarded-Proto"
          X-Forwarded-Host: "X-Forwarded-Host"
    secure-headers:
      headers:
        frameDeny: true
        sslRedirect: false
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: false
        stsIncludeSubdomains: false
        stsPreload: false
        customResponseHeaders:
          X-Powered-By: ""
